on: push
name: Publish Notes
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
	FTP_SERVER:	${{ secrets.FTP_SERVER }}
        FTP_USERNAME:	${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD:	${{ secrets.FTP_PASSWORD }}
        REMOTE_DIR:	u105021226.22web.org
        LOCAL_DIR:	htdocs
        ARGS: --verbose --delete
        # --delete arg will delete files on the server if you've deleted them in git
